#!/usr/bin/env bash

# Per https://stackoverflow.com/a/19135644 this will output all remote branches, the author, and will sort by committerdate

git for-each-ref --format='%(committerdate) %09 %(authorname) %09 %(refname)' | sort -k5n -k2M -k3n -k4n
